development: &default
  adapter: postgresql
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  timeout: 5000

test:
  <<: *default

staging:
  <<: *default

production: &default
  adapter:  postgresql
  host: localhost
  database: fss_development
  username: postgres
  password: password
