development: &default
  adapter:  postgresql
  host: localhost
  database: a4_development
  username: ahmirza
  password: password

test:
  <<: *default

staging:
  <<: *default

production: &default
  adapter:  postgresql
  host: localhost
  database: a4_prod
  username: postgres
  password: password
